export const LOAD_EDITOR_PAGE = 'app/EditorPage/LOAD_EDITOR_PAGE:ASYNC_START';
export const LOAD_EDITOR_PAGE_SUCCESS = 'app/EditorPage/LOAD_EDITOR_PAGE_SUCCESS:ASYNC_SUCCESS';
export const LOAD_EDITOR_PAGE_ERROR = 'app/EditorPage/LOAD_EDITOR_PAGE_ERROR:ASYNC_ERROR';

export const UPDATE_EDITOR_PAGE_FORM_TEMPLATE = 'app/EditorPage/UPDATE_EDITOR_PAGE_FORM_TEMPLATE';

export const UNLOCK_EDITOR_PAGE = 'app/EditorPage/UNLOCK_EDITOR_PAGE';
export const UNLOCK_EDITOR_PAGE_SUCCESS = 'app/EditorPage/UNLOCK_EDITOR_PAGE_SUCCESS';
export const UNLOCK_EDITOR_PAGE_ERROR = 'app/EditorPage/UNLOCK_EDITOR_PAGE_ERROR';

export const SAVE_EDITOR_PAGE = 'app/EditorPage/SAVE_EDITOR_PAGE:ASYNC_START';
export const SAVE_EDITOR_PAGE_SUCCESS = 'app/EditorPage/SAVE_EDITOR_PAGE_SUCCESS:ASYNC_SUCCESS';
export const SAVE_EDITOR_PAGE_ERROR = 'app/EditorPage/SAVE_EDITOR_PAGE_ERROR:ASYNC_ERROR';