export const LOAD_FORM_RESPONSES = 'app/EditorPage/Responses/LOAD_FORM_RESPONSES:ASYNC_START';
export const LOAD_FORM_RESPONSES_SUCCESS = 'app/EditorPage/Responses/LOAD_FORM_RESPONSES_SUCCESS:ASYNC_SUCCESS';
export const LOAD_FORM_RESPONSES_ERROR = 'app/EditorPage/Responses/LOAD_FORM_RESPONSES_ERROR:ASYNC_ERROR';